class_name PowerReceiver
extends Node


signal received_power(amount, delta)

@export var power_required := 10.0

@export var input_direction := 15 # (Types.Direction, FLAGS) <- auto generated by godot automatic converter

var efficiency := 0.0


func get_effective_power() -> float:
	return power_required * efficiency
